[package]
name = "segmentmap"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmaps = "3.2.0"
array-macro = "2.1.5"

[[bin]]
name = "segmentmap"
path = "benches/segmentmap.rs"
